---

name: Ansible Lint

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Lint Ansible Playbook
        # NOTE: v4.1.0 is not working
        uses: ansible/ansible-lint-action@master
        with:
          targets: ""
          args: "-q"
